mwoffliner.js

- Created a new function that add  around an element.
- Add no index comment to footnote div 
The purpose of this pull request is to create better HTML content when using omega html parser, by adding no index comments to some html elements.[reference](https://xapian.org/docs/omega/overview.html)

Xapian indexing improvement

---

package.json

Fix package versions; update repo URLs.

Some initial improvements to the package.json file

---

bin/mwmatrixoffliner.script.js
lib/mwoffliner.lib.js
package.json

MWOffliner will now create a transient parsoid instance for the currently running scraper if --localParsoid is preset.
Note this isn't working with WikiHow yet - that will need it's own scraper.

Parsoid integration

---

lib/mwoffliner.lib.js

I have added the missing callback that was missing when building the ZIM in desktop version.

bugfix for building zim not in mobile layout

---

docker/.custom-bashrc

Now the alias matches the change make in commit 419e00f13187f41303d5a74d1ba825a4cb5f0a48[](url)

Fixed the docker bashrc

---

lib/DOMUtils.js
lib/Utils.js
lib/config.js
lib/jsutils.js
lib/mwoffliner.lib.js
lib/templates/desktop.html
lib/templates/footer.html
lib/templates/mobile.html
lib/templates/redirects.html

* Updated config to point to the template files
* Updated code to read the template files

Extract templates and other code into separate files

---

README.md
lib/Downloader.js
lib/MediaWiki.js
lib/OfflinerEnv.js
lib/Zim.js
lib/mwoffliner.lib.js

There is a lot of entangled code and entangled state here.
I am beginning to do more aggressive extraction. As this goes forward, more and more components and state will end up in the right place. In the end, we'll need another pass to cleanup the refactored code to move things to where they truly belong.

More refactoring and extraction into modules

---

lib/templates/footer.html

Reduce the bottom padding of footer

less footer bottom padding

---

.eslintrc.json
.gitignore
bin/mwoffliner.script.js
lib/mwoffliner.lib.js
lib/mwoffliner.modules.js
lib/mwoffliner.vars.js

Moved imports into separate file (for globalization.)
Changed all vars into 'let' and 'const'. This gives editors more insight into the code and exposes hoisted variables, unused variables and informs us how variables are being used at a glance.
Reflowed the code per "eslint:recommended" & "prettier" settings. We use this at my work to automatically format code so our code reviews aren't about styling and more about execution. However, this PR will have the most line changes because of changes like: singleQuotes => doubleQuotes and 80Character new-lining.
Made a zim using this command: `bin/mwoffliner.script.js --mwUrl="http://en.wikipedia.org/" --adminEmail="darkenvy6@gmail.com" --articleList="wiki_list.lst" --withZimFullTextIndex --verbose`

ES6 Reflow & Refactor. Eslint's Recommended settings.

---

lib/mwoffliner.lib.js

Started over. Ensured comments were not converted. VSCode checked the code and ensured that consts are never written to again. 
Using let and const prevents hoisting. Due to variables such as "href" being used multiple times, this can help stop bugs.
http://www.jstips.co/en/javascript/keyword-var-vs-let/

Changed vars to const or let appropriately

---

lib/mwoffliner.lib.js

Converted anonymous functions to arrow functions. Following AirBNB's Javascript style guide: http://www.jstips.co/en/javascript/keyword-var-vs-let/
This also cleaned up the code and makes it more readable considering a lot of anonymous functions simply execute or do one thing.

changed anon func to arrow funcs

---

lib/templates/mobile.html

Fixed #136 - Refs section auto-opens when linked to

---

bin/mwoffliner.script.js

Add --help argument for mwoffliner

---

bin/mwoffliner.script.js

Enable --version arg with mwoffliner

---

lib/Downloader.js

While working on PR #344 I noticed that this error message would not be very helpful since we already know that the status code is 200.
I haven't tested it.  I'm not sure how to create something that would trigger this.

Include the error in the error message

---

lib/mwoffliner.lib.js

Added logging and handling invalid CSS rule urls

---

lib/mwoffliner.lib.js

Added clear error for missing site logos

---

lib/mwoffliner.lib.js
src/mwoffliner.lib.ts

#159 
I am waiting to test this better with another example of HTML tags in the title

Strip HTML from title tags

---

lib/mwoffliner.lib.js
src/mwoffliner.lib.ts

Added top level section when it doesn't exist in API Response

---

bin/mwoffliner.script.js
package.json

Bumped version and added git revision to version log

---

lib/mwoffliner.lib.js
src/mwoffliner.lib.ts

Fixed template referencing

---

bin/mwmatrixoffliner.script_test.sh

This is a step in cleaning up arg handling across mwmatrixoffliner and mwoffliner.
It's just a bash script, which I hesitated to use.  But this isn't a unit test of functions--it is testing the core actions of the whole mwmatrixoffliner script.  And I think bash is available on the command lines where mwoffliner would be run.
I am open to other ideas for how to have similar tests.

Simple test of mwmatrixoffliner

---

res/mobile.js
res/templates/lead_section_wrapper.html
res/templates/mobile.html
res/templates/section_wrapper.html

PR representing the latest changes for #324

More changes for CORS limitations

---

README.md
bin/mwoffliner.script.js
package.json
updateGitRevision.js

Updated git revision and version updating

---

Changelog

Updated Changelog

---

Changelog
lib/mwoffliner.lib.js
src/MediaWiki.ts
src/mwoffliner.lib.ts

#338 
Fixing `--addNamespace` which was accidentally comparing string to numbers

Fixed --addNamespace

---

lib/mwoffliner.lib.js
src/mwoffliner.lib.ts

Fixed broken contains compare

---

res/mobile.js

Fixed toggleOpenSection in mobile view

---

res/mobile.css

Fixed mobile CSS for images

---

res/mobile.js

Updated reference section opening (#443)

---

lib/Downloader.js
lib/mwoffliner.lib.js
lib/parameterList.js
src/Downloader.ts
src/mwoffliner.lib.ts
src/parameterList.ts

Added `useCache` option (#263)

---

README.md

I may have missed some-bits out.
Thoughts?

Re-written README

---

package-lock.json
package.json

Updated Parsoid to 0.10.0

---

lib/MediaWiki.js
lib/mwoffliner.lib.js
src/MediaWiki.ts
src/mwoffliner.lib.ts

Batch redirect fetching

---

Changelog

Updated Changelog for 1.7.0

---

package-lock.json
package.json

This is a temporary fix for #484

Disabled snyk checks on install

---

lib/mwoffliner.lib.js
lib/parameterList.js
src/mwoffliner.lib.ts
src/parameterList.ts

Removed --mcsURL

---

lib/mwoffliner.lib.js
src/mwoffliner.lib.ts

:bug: Fixed non-articleList issue

---

lib/Zim.js
src/Zim.ts

Was related to caching changes.

Fix for #504

---

.gitignore
lib/Zim.js
lib/mwoffliner.lib.js
package-lock.json
package.json
src/Zim.ts
src/mwoffliner.lib.ts
test/percy.js
tmp/.gitignore

Fixes for zim.tmpDirectory and remote articleList

---

lib/Utils.js
lib/Zim.js
src/Utils.ts
src/Zim.ts

I'm currently flying blind. I can't reproduce all of the errors you're reporting - all I can do is try to make the code more resilient.
Closes #488

More fixes for #488

---

lib/mwoffliner.lib.js
lib/redis.js
src/mwoffliner.lib.ts
src/redis.ts

Removed un-necessary comments and changed some redirect matching logic

Removed un-necessary comments and changed some redirect matching logic

---

lib/mwoffliner.lib.js
src/mwoffliner.lib.ts

Reorder pipe event registration

---

package-lock.json
package.json

Updated Packages and run npm audit fix

---

src/mwoffliner.lib.ts
src/parameterList.ts

Removed --writeHtmlRedirects option

---

.vscode/launch.json
README.md
simple-test.sh
src/mwoffliner.lib.ts
src/parameterList.ts

A few other changes

---

src/ZimCreatorFs.ts
src/mwoffliner.lib.ts
src/redis.ts

:wrench: Fixed redirect and mainPage setting in Zim creation

---

src/Dump.ts
src/mwoffliner.lib.ts
src/util/saveArticles.ts
test/percy.js

:sparkles: Removed special zim article id formatting #278

---

package-lock.json
package.json
src/Downloader.ts
src/mwoffliner.lib.ts
src/types.d.ts
src/util/redirects.ts
src/util/saveArticles.ts

Added backoff to all http requests, retries maximum 10 times with an exponential backoff pattern (see https://github.com/MathieuTurcotte/node-backoff)
Closes: #496 
I have tested this with a custom rate-limiting proxy

:sparkles: Implemented proper http request backoff

---

src/mwoffliner.lib.ts

:bug: Now properly add favicon.png

---

res/templates/article_list_home.html
src/mwoffliner.lib.ts
src/util/dump.ts
src/util/misc.ts
src/util/saveArticles.ts

:sparkles: Implemented Namespaces

---

src/MediaWiki.ts

:bug: Fix for #563 Fall back to english if language not detected

---

package-lock.json
package.json

:arrow_up: Update @openzim/libzim to fix #568

---

CONTRIBUTING.md
README.md
package.json

Any thoughts/additions @bradyhunsaker ?

:memo: Added basic TypeScript documentation for #423

---

src/mwoffliner.lib.ts

:bug: Create out directory when running #585

---

src/queues/redirectQueue.ts

:mute: Better handling of JSON error

---

README.md

:memo: Update readme #588

---

src/Downloader.ts

:bug: Downloader typo

---

src/queues/redirectQueue.ts

:bug: fixed redirect queue issue #592

---

docker/Dockerfile

:whale: Fixed Docker build #602

---

src/Downloader.ts

:truck: Improved compression logic

---

src/Downloader.ts

E.g. https://framadrop.org/r/axTlBZU4BQ#83x6hS7OxNitfbXcXEwqXOxnerN+MQDw+GTFQieXgTk=
@mossroy
Closes #605

Strip html from title #605

---

src/Templates.ts
src/mwoffliner.lib.ts
src/util/misc.ts
src/util/saveArticles.ts

:bug: Updated resource referencing

---

bin/mwoffliner.script.js

:ok_hand: CLI fix help issue #619

---

src/MediaWiki.ts
src/mwoffliner.lib.ts
src/queues/redirectQueue.ts
src/util/redirects.ts

:bug: Fix for #624

---

src/Downloader.ts
src/queues/redirectQueue.ts
src/util/saveArticles.ts

:loud_sound: Improved logging, error handling, and throttling (#622, #627)

---

src/util/dump.ts

Reduce complexity of duplicate image detection

---

src/util/dump.ts

:sparkles: performance and logic improvement

---

.vscode/launch.json
package-lock.json
package.json
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/util/redirects.ts
src/util/saveArticles.ts

:sparkles: Scraping and logging updates

---

.vscode/launch.json
Changelog
src/Downloader.ts
src/util/misc.ts
src/util/saveArticles.ts

:bug: Modifying article title logic #605

---

.vscode/launch.json
src/mwoffliner.lib.ts
src/util/redis-kvs.ts

:sparkles: Improved exit handling #448 Improved logs #662

---

.vscode/launch.json
package-lock.json
src/Downloader.ts
src/MediaWiki.ts
src/filesToDownload.ts
src/mwoffliner.lib.ts
src/parameterList.ts
src/types.d.ts
src/util/dump.ts
src/util/misc.ts
src/util/mw-api.ts
src/util/redis-kvs.ts
src/util/saveArticles.ts

:bug: :sparkles: Added category scraping flag and fixes for #684 #685 and memory/redis improvements

:bug: :sparkles: Added category scraping flag and fixes for #684 #685 and memory/redis improvements

---

res/mobile_main_page.css

Welcome page images with white background

---

src/Downloader.ts

:bug: Adds a check before normalizing query (#698)

---

src/Dump.ts
src/mwoffliner.lib.ts

:bug: re-added tags (#709)

---

src/Downloader.ts
src/util/saveArticles.ts

:wrench: Increased wt2html limits #710

---

.vscode/launch.json
package-lock.json
package.json
res/article_list_home.js
res/details_polyfill.js
res/script.js
res/style.css
res/templates/article_list_home.html
res/templates/lead_section_wrapper.html
res/templates/section_wrapper.html
res/templates/subcategories.html
res/templates/subpages.html
res/templates/subsection_wrapper.html
src/Downloader.ts
src/config.ts
src/mwoffliner.lib.ts
src/util/articleRenderers.ts
src/util/saveArticles.ts

Category scraping improvements and article collapsing changes
See generated ZIM: https://framadrop.org/r/cYeF-hsrXN#UWwvdi4IR2uEx/z7JkzgSYLUrlObAgrjQml0zUOLmIA=
Tested and working on KiwixJS and Kiwix Mac 
Closes: #677

:sparkles: Progress on #15 and implemented #677

---

src/util/saveArticles.ts

:bug: fix url rewriting (#726)

---

src/mwoffliner.lib.ts

:bug: properly clear down redis after exit (#731)

---

src/mwoffliner.lib.ts

Speed-up default speed

---

res/templates/article_list_home.html
src/mwoffliner.lib.ts

:bug: fix the no-image article list view

---

package.json
src/mwoffliner.lib.ts
src/stores.ts
src/util/saveArticles.ts

Image download retry changes

---

res/templates/subcategories.html
src/Downloader.ts
src/Dump.ts
src/MediaWiki.ts
src/types.d.ts
src/util/articleRenderers.ts
src/util/categories.ts
src/util/redis-kvs.ts
src/util/saveArticles.ts

Example:
https://framadrop.org/r/taT5kYRAfz#uOVi5c+XqoocqOHh0fMjJ2Dk5j2Cbi55a44bVUl1cLg=
Look at the "Category:Container categories" article

:sparkles: add pagination for subcategories

---

src/Downloader.ts

More minor changes

---

src/Downloader.ts

:bug: fix sub-category scraping log #778

---

src/Downloader.ts
src/mwoffliner.lib.ts
src/util/saveArticles.ts

Tidy API Requests

---

src/mwoffliner.lib.ts
src/util/misc.ts
src/util/redis-kvs.ts

throttled keepalive log

---

src/Dump.ts
test/unit/urlRewriting.test.ts

:white_check_mark: more tests and bug fixes (#726)

---

src/Downloader.ts

:bug: only fetch relevant namespaces redirects (#790)

---

res/templates/subsection_wrapper.html

:bug: set subsections to open by default (#786)

---

test/unit/saveArticles.test.ts

:white_check_mark: add geo tag tests (#795)

---

res/mobile_main_page.css
res/templates/article_list_home.html
src/mwoffliner.lib.ts

:bug: fix no-image aritcle home page (#759)

---

src/mwoffliner.lib.ts

:loud_sound: add Scraper metadata to outputted ZIM file (#787)

---

src/util/saveArticles.ts

:bug: disable quirks mode for article html (#717)

---

src/Dump.ts

Fix offline.css retrieval

---

src/util/rewriteUrls.ts
test/e2e/bm.e2e.test.ts
test/e2e/en10.e2e.test.ts
test/unit/sanity.test.ts
test/unit/saveArticles.test.ts
test/unit/urlRewriting.test.ts
test/util.ts
tsconfig.json

:label: fix typescript path issue

---

docker/Dockerfile

Custom ulimits

---

src/util/articleRenderers.ts
src/util/dump.ts
test/unit/styles.test.ts

minor bug fixes

---

README.md
src/mwoffliner.lib.ts
src/parameterList.ts
src/util/categories.ts
src/util/mw-api.ts
src/util/saveArticles.ts

Closes #827 
Closes #824 
Closes #822 
Closes #740

A few minor fixes

---

src/Downloader.ts
src/mwoffliner.lib.ts
src/parameterList.ts
test/unit/downloader.test.ts

More minor tweaks

---

src/mwoffliner.lib.ts
src/util/misc.ts
test/e2e/bm.e2e.test.ts
test/e2e/en10.e2e.test.ts

Redis cleardown fix

---

src/Downloader.ts
src/Dump.ts
test/unit/downloader.test.ts

:sparkles: add check for offline.css (#614)

---

src/util/dump.ts
src/util/misc.ts
src/util/rewriteUrls.ts
src/util/saveArticles.ts
test/unit/urlRewriting.test.ts

:sparkles: re-write urls with no protocol (#640)

---

src/util/saveArticles.ts

:art: simplification of saveArticles (#687)

---

src/Dump.ts
src/mwoffliner.lib.ts
test/e2e/bm.e2e.test.ts
test/e2e/en10.e2e.test.ts

:construction: :white_check_mark:  progress on #851

---

src/util/rewriteUrls.ts
src/util/saveArticles.ts
test/unit/urlRewriting.test.ts
test/util.ts

Closes #842 
Closes #815 
Closes #745

Audio scraping improvements

---

src/util/saveArticles.ts
test/e2e/en10.e2e.test.ts
test/unit/saveArticles.test.ts

@kelson42 I don't really understand the old logic, but I believe this does the same thing...

:sparkles: :white_check_mark: re-write empty paragraph removal logic

---

src/util/rewriteUrls.ts
src/util/saveArticles.ts
test/e2e/en10.e2e.test.ts
test/unit/saveArticles.test.ts
test/unit/urlRewriting.test.ts

Closes #771 
The issue was an ordering issue.
I've updated the tests to use complex (with `/`) parent article ids, which showed a few other bugs that are solved by this minor code-change

fix a few url rewriting issues and update tests

---

src/mwoffliner.lib.ts
src/util/mw-api.ts
src/util/saveArticles.ts
test/e2e/en10.e2e.test.ts
test/unit/saveArticles.test.ts

Minor fixes

---

src/util/mw-api.ts
src/util/saveArticles.ts
test/e2e/en10.e2e.test.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/unit/saveArticles.test.ts
test/unit/urlRewriting.test.ts

@kelson42 I think this covers your requests here: https://github.com/openzim/mwoffliner/pull/847

:white_check_mark: MWApi and URLRewriting tests

---

src/mwoffliner.lib.ts

:bug: only fetch thumbnails for articles displayed in article list homepage (#867)

---

src/mwoffliner.lib.ts
src/util/saveArticles.ts
test/e2e/en10.e2e.test.ts
test/unit/saveArticles.test.ts

:sparkles: detect when mobile view is not available and don't try fetching it

---

src/util/categories.ts
src/util/mw-api.ts
src/util/saveArticles.ts

Fix percentage computation

---

README.md

Clarify a bit the local launch cmd

---

.github/stale.yml

Better follow which tickets/PRs need to be updated

Introduce stalebot configuration

---

src/util/saveArticles.ts
test/unit/saveArticles.test.ts

:bug: empty paragraph removal for both mobile and desktop view (#857)

---

src/Downloader.ts
src/Dump.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/util.ts

:sparkles: Check mw capabilities before starting scrape

---

src/util/articleRenderers.ts

:bug: remove hard-coded Disambiguation section (#872)

---

res/style.css

No pointer cursor for <h1> article title

---

src/config.ts

Kind of hack to display WPEN videos #900

---

CONTRIBUTING.md
README.md

This basically the same content as before just reorganised a bit between the sections and with a stricter separation between the README.md (for users) and the CONTRIBUTING.md (for developers).

README.md & CONTRIBUTING.md revamp

---

.travis.yml
dev/hackPackageVersion.js
dev/publish.sh

Not sure how this will work with the three builds...

:construction_worker: Automatically deploy to npmjs when tagged (#556)

---

res/script.js

:bug: avoid passing complex ids to jQuery (#136)

---

res/mobile_main_page.css

:bento: specify tile layout for screens ~8096px (#617)

---

src/mwoffliner.lib.ts
src/stores.ts
src/util/dump.ts
src/util/misc.ts
src/util/saveArticles.ts

:ok_hand: only store namespace and mult of media if necessary

---

src/util/articleListMainPage.ts

:bug: fix article list homepage links to articles with '/' (#911)

---

.travis.yml
dev/install-zimtools.sh
package-lock.json
package.json
res/details_polyfill.js
src/config.ts
test/e2e/bm.e2e.test.ts
test/e2e/en10.e2e.test.ts
test/util.ts

add zimcheck to e2e tests

---

src/Downloader.ts
src/mwoffliner.lib.ts
src/stores.ts
src/util/dump.ts
src/util/mw-api.ts
src/util/saveArticles.ts
test/unit/bootstrap.test.ts

Request Cache logic changes

---

src/DOMUtils.ts
src/util/rewriteUrls.ts

:bug: fix broken attribute appending and mw:ExtLink detection

---

src/util/mw-api.ts

:bug: add more safety to string replace and a warning (#793)

---

.travis.yml

Fix 'find' command to get zimcheck path

---

src/mwoffliner.lib.ts

:bug: fix mainPage detection (#925)

---

src/mwoffliner.lib.ts
src/parameterList.ts

:fire: remove skipCacheCleaning argument

---

src/mwoffliner.lib.ts

Fix ZIM description metadata

---

Changelog
src/Dump.ts
src/mwoffliner.lib.ts

Add new Flavour ZIM metadata

---

src/Dump.ts

Fix file extension detection

---

src/config.ts

:sparkles: keep mwe-math-mathml-inline HTML (#164)

---

src/util/saveArticles.ts

:sparkles: replace kartographer maplink "1" with world emoji (#871)

---

src/ZimCreatorFs.ts
src/util/RedisKvs.ts
src/util/mw-api.ts
src/util/redirects.ts
test/unit/bootstrap.test.ts
test/unit/redis.test.ts

:sparkles: remove duplicate article data for redirects (#889)

---

res/templates/section_wrapper.html
res/templates/subsection_wrapper.html
src/util/articleRenderers.ts

:bug: fix article section rendering (#872)

---

res/script.js
res/style.css

Fix #931
@Popolechien will be pleased 😅

:poop: add KAIOS title hack (#931)

---

res/script.js
res/templates/section_wrapper.html

:bug: support no-js mobile rendering better (#962)

---

package-lock.json
package.json
src/util/misc.ts
test/e2e/bm.e2e.test.ts
test/e2e/cmd.e2e.test.ts
test/e2e/en10.e2e.test.ts
test/e2e/extra.e2e.test.ts
test/util.ts

:arrow_up: use execa instead of execPromise

---

Changelog
src/Dump.ts

Details tag fix

---

Changelog
src/cli.ts
src/parameterList.ts

Add new --osTmpDir optional argument

---

src/util/saveArticles.ts
test/unit/saveArticles.test.ts

:bug: stop removing non-empty sections (#986)

---

src/Dump.ts
test/unit/urlRewriting.test.ts

Closes #726
Looks like there was a bug & a test was incorrect.

:bug: fix url escaping (#726)

---

src/util/saveArticles.ts

Should resolve #1024 
- Removed recursion
- Introduced one missing error callback
- Provided a precautious try-catch block

Recursion removed and error callback introduced

---

src/S3.ts

Error rejection handled in S3 module

---

src/Downloader.ts
src/util/saveArticles.ts

Adding Meaningful Error Logs

---

src/S3.ts

Axios err callback introduced

---

src/mwoffliner.lib.ts
src/util/saveArticles.ts

It should resolve:
1.  #1043 
2. Some images not getting scarped in some articles.

Parallel process of downloading changed

---

src/Downloader.ts

Removed getContent recursive callback when status is 429

---

src/util/saveArticles.ts

Improve logging 

---

.npmignore

added more test stuff to .npmignore

---

package-lock.json
src/Downloader.ts
src/util/mw-api.ts

Changed getArticleDetailsIds and getArticleDetailsNS from recursive to iterative

---

src/Downloader.ts
src/util/const.ts

Throwing error and stopping MWOffliner when MwAPI is not successful

---

package-lock.json
package.json
src/S3.ts

S3 logging improved

---

src/Downloader.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/parameterList.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/util.ts

Option to force local Parsoid + refactoring

---

src/mwoffliner.lib.ts
src/util/misc.ts
test/unit/util.test.ts

Setting title for main page

---

src/Downloader.ts
src/mwoffliner.lib.ts
src/types.d.ts
src/util/articleRenderers.ts
src/util/misc.ts
src/util/saveArticles.ts
test/unit/util.test.ts

- Fix: fallback / source select logic and related
- Fix: title rendering for the sources scraped using `visualeditor` (#1058)
- Refactoring

fix source select logic + inject header to the page

---

CONTRIBUTING.md
res/style.css
res/templates/footer.html
src/Downloader.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/types.d.ts
src/util/articleRenderers.ts
src/util/saveArticles.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/util.ts

@kelson42 Once we merge this, could you please change `mwWikiPath` flag for `edutech` recipes to be:
```
--mwWikiPath=./
```
(I have no permissions for that).
This bug would impact other sources that have `mwWikiPath: index.php` (we have 23 total), so we need to change them accordingly.
@bakshiutkarsha in this branch based on the changes made in PR #1089, please don't be confused by many commits here (actually, here are only 3 commits). Once you approved #1089, I'll rebase this one and number of commits here will be reduced ;)
Fixes #1059

Fixes for edutech + refactoring

---

.codecov.yml
src/Dump.ts
src/mwoffliner.lib.ts
src/util/articleListMainPage.ts
src/util/misc.ts
src/util/rewriteUrls.ts
src/util/saveArticles.ts
test/unit/dump.test.ts
test/unit/util.test.ts

should resolve #1024 
Tested with following articles:
Que faire ?
Que faire ? (Lénine)
Avanti!
and some regular articles.

Fix for the articles with question mark

---

test/unit/downloader.test.ts

should resolve #1110 .
This test case has already been taken care in S3 test file.

removed duplicate test

---

.travis.yml
CONTRIBUTING.md
package.json

npm run test:e2e added

---

src/mwoffliner.lib.ts
src/util/saveArticles.ts
test/unit/saveArticles.test.ts
tslint.json

Fixes #1081
Fix OOM + refactoring
Tested with same conditions on GCP.

remove unnecessary async wrapper + refactoring

---

translation/es.json

Add Spanish translation

---

dev/publish.sh

Fixes #556 
@kelson42 not sure how this tag is being handled on docker hub side. Is that we need to do here?

Add `latest` tag

---

src/mwoffliner.lib.ts
src/util/mw-api.ts

Fix wrong log msg about namespace total articles

---

src/Downloader.ts

Remove logging that don't used anymore

---

src/Downloader.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/parameterList.ts
src/types.d.ts
src/util/misc.ts
test/unit/downloader.test.ts

Rest API url refactoring

---

src/Downloader.ts
src/MediaWiki.ts
src/util/misc.ts

Fixes #1153
Not sure if there's another things to do in this issue. @kelson42 please correct me if I'm wrong.

Minor renaming + fix the bug with slash

---

src/util/const.ts
src/util/misc.ts
src/util/mw-api.ts
test/unit/urlRewriting.test.ts
test/unit/util.test.ts

Small improvements without big impacts

---

src/Downloader.ts
src/util/articleRenderers.ts
test/unit/saveArticles.test.ts

Remove fallback logic + cleanup + small refactoring

---

src/Redis.ts
src/config.ts

Use normal default config for redis

---

src/Downloader.ts
src/MediaWiki.ts
src/util/dump.ts
src/util/rewriteUrls.ts
src/util/saveArticles.ts
test/unit/saveArticles.test.ts

Add url host and protocol in mediawiki class

---

src/Downloader.ts
src/util/articleRenderers.ts
test/unit/downloader.test.ts

Some fixes to Downloader and MW classes logic 
Fixes #1190
Probably affects #1139
Alternative fix for #1146

Scraping of non wikimedia Mediawiki seems broken

---

src/Downloader.ts
src/MediaWiki.ts
src/util/dump.ts
src/util/rewriteUrls.ts
src/util/saveArticles.ts

Store URLs as URL objects

---

articlelist.txt
src/Dump.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/types.d.ts
src/util/saveArticles.ts

Removing concept of spaceDelimiter from MWOffliner

---

.travis.yml
package-lock.json
package.json

Bump-up node-libzim to 2.3.0

---

src/Downloader.ts
src/Dump.ts
src/util/articleRenderers.ts
src/util/saveArticles.ts

customMainPage for wikitionary

---

articlelist.txt
src/Dump.ts
src/MediaWiki.ts
src/types.d.ts
src/util/dump.ts
src/util/misc.ts
src/util/rewriteUrls.ts
src/util/saveArticles.ts
test/unit/saveArticles.test.ts
test/unit/util.test.ts

getFullUrl Rewritten

---

package-lock.json
src/Downloader.ts
src/S3.ts
src/mwoffliner.lib.ts
test/e2e/en10.e2e.test.ts

optionRequest Extracted

---

src/util/saveArticles.ts

Skipped one folder for Subpage

---

src/Dump.ts

Css offline url changed

---

src/cli.ts
src/sanitize-argument.ts

Adding tests for arguments in the beginning of the process. for issue #990

Sanitize command line arguments

---

test/unit/saveArticles.test.ts

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/openzim/mwoffliner/issues).

Apply fixes from CodeFactor

---

Changelog
src/mwoffliner.lib.ts
src/parameterList.ts

Add ability to make ZIM files using Zstdandard compression

---

src/Downloader.ts
src/util/mw-api.ts
src/util/redirects.ts

Fixes #984 and #1073 and #1247

Handle redirects at a low level

---

src/Downloader.ts
src/util/articleRenderers.ts
test/e2e/localParsoid.test.ts

Fix local parsoid scenario

---

src/util/dump.ts
src/util/saveArticles.ts

@MananJethwani Few fixes on the latest wepb big PR. Most important is the proper reading of Webp polyfill, even if current directory is not mwoffliner source code root.

Few small fixes

---

CONTRIBUTING.md
package.json

@MananJethwani here is how to properly run only one test

Improve automated tests usability

---

res/script.js
res/templates/page.html
src/util/saveArticles.ts

@kelson42 this solves #1286 
here is a zim file for you to test
[zimfile_with_webp.zip](https://github.com/openzim/mwoffliner/files/5446417/zimfile_with_webp.zip)

added polyfill script

---

res/script.js
res/templates/article_list_home.html
src/mwoffliner.lib.ts
src/util/articleListMainPage.ts

added webp to main page

---

src/util/mw-api.ts
test/unit/webpAndRedirection.test.ts

corrected redirection

---

src/Downloader.ts
src/util/saveArticles.ts
test/e2e/localParsoid.test.ts

changes to solve rendering pb of license in footer

---

src/Downloader.ts
src/util/articleListMainPage.ts
src/util/const.ts
src/util/misc.ts
src/util/saveArticles.ts
test/unit/downloader.test.ts
test/unit/saveArticles.test.ts
test/unit/util.test.ts
test/unit/webpAndRedirection.test.ts

Mime type check

---

src/Downloader.ts

Forbid redirects in APIs detection

---

src/Downloader.ts
src/mwoffliner.lib.ts

Fix broken detection of APIs

---

src/util/mw-api.ts

removed batchSize concept and started use of maxBatchSize

---

src/util/saveArticles.ts

added condition to remove a para when only summary present

---

res/script.js

added condition for only one para

---

res/script.js
res/templates/article_list_home.html
src/Templates.ts
src/config.ts
src/mwoffliner.lib.ts
src/util/dump.ts
src/util/misc.ts
src/util/saveArticles.ts
test/unit/saveArticles.test.ts
test/unit/urlRewriting.test.ts
test/unit/util.test.ts
test/unit/webpAndRedirection.test.ts

@kelson42 this resolves #1302 
do let me know if something else needed to be removed I assume js/jsModules and style/styleModulle needs to be merged as well

removed m dir from default configuration

---

src/util/const.ts
src/util/misc.ts
test/e2e/extra.e2e.test.ts
test/unit/util.test.ts

added test for png with ?(hieroglyphs images)

---

src/MediaWiki.ts
src/cli.ts
src/mwoffliner.lib.ts
src/sanitize-argument.ts
src/util/const.ts
test/e2e/extra.e2e.test.ts

this temporarily resolves #1322

fixing url check for mobile page

---

src/Downloader.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/sanitize-argument.ts

added proper support for logging in for mediawiki 1.28+

---

src/Downloader.ts
src/Dump.ts
src/MediaWiki.ts

added methods in mediawiki and download class for url

---

src/config.ts

added listing-sister-icon to cssblacklistClass

---

src/Downloader.ts
test/unit/downloader.test.ts

using sharp to convert image color-space to rgb for webp

---

src/Downloader.ts

removed accept header from ArrayBufferRequestOption

---

src/util/saveArticles.ts

correcting the removal of paragraph

---

README.md

Update README.md with more details about npm and deps

---

src/cli.ts

added errorHandler and used it to catch unhandled errors

---

src/Downloader.ts
src/util/saveArticles.ts
test/unit/saveArticles.test.ts

@kelson42 this is to resolve #1329

stopping process when an article Id fails

---

src/MediaWiki.ts

added check for mediawiki version

---

src/Dump.ts

Remove surnumerous underscore in M/Flavour

---

.github/workflows/ci.yml

Add Node.js 15.x to the CI

---

src/util/saveArticles.ts

not killing process on 404 response

---

src/Downloader.ts

Better check remote API

---

src/util/articleListMainPage.ts
src/util/misc.ts
src/util/rewriteUrls.ts
test/unit/util.test.ts

corrected paths for articles starting with /

---

src/MediaWiki.ts

corrected position of & in lgdomain url

---

src/util/const.ts
src/util/misc.ts
test/unit/util.test.ts

handled score extension images

---

src/Downloader.ts
src/MediaWiki.ts

changed URI key to use getApiQueryUrl in parsoid

---

src/MediaWiki.ts

added check for mwVersion

---

src/util/mw-api.ts
test/unit/util.test.ts

corrected page title retrieval in normalizeMwResponse

---

src/Downloader.ts

added redirect option for api-availablity and added condition for domain check

---

.github/workflows/ci.yml
package-lock.json
package.json
src/Downloader.ts
test/unit/mwApi.test.ts

Parsoid custom url fix

---

test/e2e/localParsoid.test.ts

@kelson42 I have updated parsoid test, but the test won't close similar to #1278.
so currently I have deactivated the tests.

changed localParsoid e2e test

---

src/mwoffliner.lib.ts

Better indgest Windows encoded article lists

---

src/Downloader.ts
src/util/dump.ts
test/e2e/en10.e2e.test.ts
test/e2e/extra.e2e.test.ts
test/unit/mwApi.test.ts

@kelson42 this fixes tests and a minor bug I found from the last merged PR looks like rgaudin forgot to change variable name from `webpHandlerUrl` to `WEBP_HANDLER_URL` and we merged it.

Fix redirect retrieval if > 500 redirects

---

src/Downloader.ts
src/util/mw-api.ts
test/e2e/extra.e2e.test.ts

fixed articleId encoding

---

src/mwoffliner.lib.ts

Reduce default speed (parallelization) by 30%

---

src/util/rewriteUrls.ts
test/e2e/wikisource.e2e.test.ts

Catch url.parse call to avoid crashing

---

src/util/saveArticles.ts
test/unit/saveArticles.test.ts

changed video source for better resolution

---

src/util/saveArticles.ts
test/unit/saveArticles.test.ts

audio tag fix

---

src/util/mw-api.ts
test/e2e/extra.e2e.test.ts

New attempt fixing 1464

---

src/util/saveArticles.ts
test/unit/saveArticles.test.ts

Minor video source resolution bug fix

---

src/mwoffliner.lib.ts
src/util/saveArticles.ts

This is an attempt to fix #1456

Allow to have JSON error 'missingarticle' in module dependence retrieval

---

package-lock.json
src/Downloader.ts

Fix to workaround Wikimedia backend bug

---

src/mwoffliner.lib.ts
src/util/const.ts

Fixes #622
in particular in system with a lots of CPU cores.

Limit speed

---

src/mwoffliner.lib.ts

Few favicon bug fixes

---

src/Downloader.ts

Use TCP keepalive

---

res/content.parsoid.css
src/util/saveArticles.ts

Coming in Parsoid's content version 2.5.0
Bug: [T273505](https://phabricator.wikimedia.org/T273505)

Add support for mw:File typeof

---

.github/workflows/ci.yml
README.md

Drop support for Node 14.x

---

README.md

Add libglu1 to README

---

src/config.ts

This fixes https://github.com/openzim/mwoffliner/issues/1033.
Superseeds #1665

Hardcoded list of gadget resources to import

---

src/MediaWiki.ts

Following a comment https://github.com/openzim/mwoffliner/issues/1707#issuecomment-1370150119

Remove deprecated link treatment

---

test/e2e/en10.e2e.test.ts
test/e2e/extra.e2e.test.ts

A few test articles have been removed from WPEN

---

test/e2e/extra.e2e.test.ts

fix subpage code coverage

---

test/unit/downloader.test.ts

Set delay to wait until S3 uploading finished

---

Changelog
package.json

Release 1.12.0

---

translation/fr.json
translation/ia.json
translation/nl.json
translation/sc.json

Localisation updates from https://translatewiki.net.

---

src/sanitize-argument.ts
test/e2e/bm.e2e.test.ts
test/e2e/cmd.e2e.test.ts

added test for option addNamespaces

---

docker/Dockerfile

Use ghcr.io as source for node-redis

---

src/sanitize-argument.ts
test/e2e/cmd.e2e.test.ts

Add the value of "verbose" parameter into the log, to debug why the script is stops

Added value of "verbose" parameter into the log if it is invalid.

---

Changelog
package-lock.json
package.json

Release 1.13.0

---

src/MediaWiki.ts

Remove 'local dialect' from upstream lang code

---

src/Downloader.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/unit/renderers/renderer.builder.test.ts
test/unit/saveArticles.test.ts
test/unit/urlRewriting.test.ts
test/util.ts

Fixes https://github.com/openzim/mwoffliner/issues/1888

Move hasCoordinates to Mediawiki singleton

---

src/Downloader.ts
test/e2e/downloadImage.e2e.test.ts

Fixes https://github.com/openzim/mwoffliner/issues/1904

Convert S3 response body from IncomingMessage object to Buffer

---

src/config.ts
src/renderers/abstract.renderer.ts
src/util/mw-api.ts
test/unit/saveArticles.test.ts

Fix https://github.com/openzim/mwoffliner/issues/1868

Fix nodet format option

---

src/mwoffliner.lib.ts
src/util/const.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/unit/renderers/renderer.builder.test.ts
test/unit/saveArticles.test.ts
test/util.ts

Fixes https://github.com/openzim/mwoffliner/issues/1940
Depends on https://github.com/openzim/mwoffliner/pull/1944

Reintroduce VisualEditor capability check

---

test/e2e/wikisource.e2e.test.ts

Manually verified with this revision:
https://fo.wikisource.org/w/index.php?title=Fors%C3%AD%C3%B0a&oldid=3466

Change expectations of files number on fo wikisource main page

---

test/e2e/vikidia.e2e.test.ts

Skip vikidia e2e test

---

test/unit/downloader.test.ts

Update test, Zürich now redirects to Zurich

---

src/mwoffliner.lib.ts

Properly await async polyfill function to avoid race condition

---

README.md
package-lock.json
package.json

Clarification around Node.js supported versions

---

package.json

Update version for logs and ZIM files

---

res/mobile_main_page.css

Fix https://github.com/openzim/mwoffliner/issues/1972
| Before | After |
|--|--|
| ![Screenshot 2025-02-18 at 14 27 13](https://github.com/user-attachments/assets/df1dfdec-0ab4-45aa-986d-14816894d188) | ![Screenshot 2025-02-18 at 14 33 38](https://github.com/user-attachments/assets/86288dc8-e009-4546-b4ed-17e80645f19c) |

Fix width of thumbnails caption to avoid overflow

---

dev/build.sh
test/unit/util/metaData.test.ts
tsconfig.json

Fix #2130
Changes: see commits message

Fix silent build errors

---

test/e2e/zimMetadata.e2e.test.ts

Fix ZIM metadata checks

---

Changelog
src/parameterList.ts
src/util/mw-api.ts

Ignore pages without a single revision / revid - continued

---

Changelog
src/mwoffliner.lib.ts

Set proper mimetype for ZIM illustration(s) metadata

---

README.md

Enhance README documentation around installation, contributing and scraper background

---

Changelog
src/Downloader.ts
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/renderers/abstract.renderer.ts
src/renderers/abstractDesktop.render.ts
src/renderers/action-parse.renderer.ts
src/renderers/renderer.builder.ts
src/renderers/wikimedia-mobile.renderer.ts
src/util/categories.ts
src/util/dump.ts
src/util/misc.ts
src/util/mw-api.ts
src/util/saveArticles.ts
test/unit/downloader.test.ts
test/unit/mwApi.test.ts
test/unit/mwApiCapabilities.test.ts
test/unit/renderers/article.renderer.test.ts
test/unit/renderers/renderer.builder.test.ts
test/unit/saveArticles.test.ts
test/unit/treatments/article.treatment.test.ts
test/unit/urlRewriting.test.ts
test/unit/util.test.ts
test/unit/util/dump.test.ts
test/util.ts

fix: #2154 
Create a Downloader singleton to stop passing object around

Refactor: create a Downloader singleton to stop passing object around

---

Changelog
package-lock.json
package.json

Upgrade to node-libzim 3.3.0

---

Changelog
src/mwoffliner.lib.ts

Properly download all CSS dependencies on all flavors

---

Changelog
src/renderers/error.render.ts
test/unit/misc.test.ts
translation/en.json
translation/qqq.json

Add more error catching with placeholder replacement

---

Changelog
src/MediaWiki.ts
src/mwoffliner.lib.ts
src/parameterList.ts
src/sanitize-argument.ts
src/types.d.ts
test/e2e/apiPathParamsSanitizing.e2e.test.ts
test/unit/mwApi.test.ts

Links to articles through index.php are not detected properly

---

Changelog
src/Dump.ts
src/S3.ts
src/mwoffliner.lib.ts
src/renderers/error.render.ts
src/sanitize-argument.ts
src/util/dump.ts
src/util/rewriteUrls.ts
src/util/url.helper.ts
test/unit/downloader.test.ts
test/unit/s3.test.ts
test/unit/saveArticles.test.ts

Replace urlparser deprecated API with WHATWG URL API

---

src/renderers/action-parse.renderer.ts

Small bug discovered in recent change of https://github.com/openzim/mwoffliner/pull/2291

Throw err when it is not expected kind

---

src/mwoffliner.lib.ts
src/util/dump.ts
src/util/misc.ts
src/util/saveArticles.ts
src/util/url.helper.ts
test/unit/util/dump.test.ts
test/unit/util/url.helper.test.ts

Fix url serialization and set `FRONT_ARTICLE` hint everywhere

---

src/Downloader.ts

Fix #2314 
This PR is linked to issues we've had on multiple tasks:
- https://farm.openzim.org/pipeline/62bfb307-1306-4d6a-9ed7-8bb268c0317c/debug
- https://farm.openzim.org/pipeline/da12f873-96a3-4ab9-a887-c62d803f7452/debug
- https://farm.openzim.org/pipeline/997b2b8f-29f2-4989-9a3a-f85354575772/debug
- https://farm.openzim.org/pipeline/d4a70e18-8dfc-478b-b9e9-4ff69d2ece81/debug
- https://farm.openzim.org/pipeline/ed19790c-b390-4ca7-a880-374cf5202329/debug
All these seems to be very transient errors we should have retried.
Changes:
- Retry all AxiosError codes except 'ERR_BAD_REQUEST' (which are raised when HTTP error occurs), all of them are expectable to be transient
- Add AxiosError code to the download error context, so that we can log it properly and act on it if we decide to
- Log …

Harden handling of AxiosError

---

Changelog
src/error.manager.ts
test/unit/misc.test.ts
translation/en.json
translation/qqq.json

Add support for internal_api_error_Error errors

---

Changelog
src/error.manager.ts
test/unit/misc.test.ts
translation/en.json
translation/qqq.json

Handle empty HTTP response

---

Changelog
src/error.manager.ts
test/unit/misc.test.ts
translation/en.json
translation/qqq.json

Handle invalid argument exceptions

---

Changelog
src/renderers/renderer.builder.ts
test/unit/renderers/renderer.builder.test.ts

Fix #2183 
~~[WIP] Do not merge until we are sure we won't release a 1.15.1 or other patch versions~~

ActionParse renderer is now the preferred one when available

---

Changelog
src/renderers/abstract.renderer.ts
src/util/dump.ts
test/e2e/bm.e2e.test.ts
test/unit/util/dump.test.ts

Also rewrite inline <style> tags found in article HTML

---

Changelog
src/Downloader.ts
src/renderers/abstract.renderer.ts
src/renderers/action-parse.renderer.ts
src/renderers/rest-api.renderer.ts
src/renderers/visual-editor.renderer.ts
src/renderers/wikimedia-mobile.renderer.ts
src/util/builders/url/action-parse.director.ts
test/e2e/displayTitle.e2e.test.ts

Make ActionParse renderer respect custom display titles

---

Changelog
src/Downloader.ts

Retry 500 HTTP errors as well

---

Changelog
src/renderers/abstract.renderer.ts

Stop removing links around images

---

Changelog
src/config.ts
src/renderers/abstract.renderer.ts

Keep all HTML tags from parser, since they might be used by CSS (especially for backlinks)

---

Changelog
src/util/saveArticles.ts

Request lead section with nodet only for wikitext pages

---

Changelog
src/util/builders/url/action-parse.director.ts

Fix #2449
Disable the TOC for all skins as this feature should be provided by the reader.

Disable the TOC for all skins

---

Changelog
src/util/articles.ts
test/e2e/en.e2e.test.ts
test/unit/util/articles.test.ts

Don't reserve space for elements that don't exist

---

Changelog
src/renderers/action-parse.renderer.ts
src/util/saveArticles.ts

Get the whole article when the specified section is not available

---

Changelog
src/Downloader.ts
src/util/mw-api.ts

Add redirects from all acceptable namespaces

---

Changelog
src/Downloader.ts

Retry all Mediawiki errors except few known ones deemed to fail

---

Changelog
src/renderers/abstract.renderer.ts
test/unit/renderers/processHtml.test.ts

Remove any iframe in article content

---

Changelog
package-lock.json
package.json

Upgrade to node-libzim 3.5.0
